-- Pisipouk Supabase schema snapshot
-- Generated 2026-09-21 from project gqpbskssrvpfjtujwezc
-- Schema only: no production rows and no secrets are stored here.

create extension if not exists pgcrypto;

-- pisipouk_messages
create table if not exists public."pisipouk_messages" (
  "id" uuid not null default gen_random_uuid(),
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "name" text not null,
  "phone" text not null,
  "email" text,
  "child_age" text,
  "preferred_contact" text,
  "message" text,
  "consent" boolean not null default false,
  "status" text not null default 'new'::text check (status = ANY (ARRAY['new'::text, 'contacted'::text, 'appointment'::text, 'enrolled'::text, 'closed'::text, 'spam'::text])),
  "source" text not null default 'website'::text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "admin_notes" text,
  "follow_up_at" timestamp with time zone,
  "last_contacted_at" timestamp with time zone,
  "archived" boolean not null default false,
  primary key ("id")
);

alter table public."pisipouk_messages" enable row level security;

-- pisipouk_reviews
create table if not exists public."pisipouk_reviews" (
  "id" uuid not null default gen_random_uuid(),
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "source" text not null default 'google'::text,
  "source_url" text,
  "external_id" text,
  "reviewer_name" text,
  "rating" numeric not null check (rating >= 1::numeric AND rating <= 5::numeric),
  "review_text" text,
  "review_date" date,
  "verified" boolean not null default false,
  "is_featured" boolean not null default false,
  "is_published" boolean not null default false,
  primary key ("id")
);

alter table public."pisipouk_reviews" enable row level security;

-- pisipouk_settings
create table if not exists public."pisipouk_settings" (
  "key" text not null,
  "value" jsonb not null,
  "is_public" boolean not null default true,
  "updated_at" timestamp with time zone not null default now(),
  primary key ("key")
);

alter table public."pisipouk_settings" enable row level security;

-- pisipouk_admin_credentials
create table if not exists public."pisipouk_admin_credentials" (
  "id" integer not null default 1 check (id = 1),
  "salt" text not null,
  "password_hash" text not null,
  "updated_at" timestamp with time zone not null default now(),
  primary key ("id")
);

alter table public."pisipouk_admin_credentials" enable row level security;

-- pisipouk_admin_sessions
create table if not exists public."pisipouk_admin_sessions" (
  "id" uuid not null default gen_random_uuid(),
  "token_hash" text not null,
  "created_at" timestamp with time zone not null default now(),
  "expires_at" timestamp with time zone not null,
  "last_seen_at" timestamp with time zone not null default now(),
  primary key ("id")
);

alter table public."pisipouk_admin_sessions" enable row level security;

-- pisipouk_admin_audit
create table if not exists public."pisipouk_admin_audit" (
  "id" bigint not null default nextval('pisipouk_admin_audit_id_seq'::regclass),
  "created_at" timestamp with time zone not null default now(),
  "action" text not null,
  "entity_type" text,
  "entity_id" text,
  "details" jsonb not null default '{}'::jsonb,
  primary key ("id")
);

alter table public."pisipouk_admin_audit" enable row level security;

-- pisipouk_leads
create table if not exists public."pisipouk_leads" (
  "id" uuid not null default gen_random_uuid(),
  "created_at" timestamp with time zone not null default now(),
  "parent_name" text not null,
  "phone" text not null,
  "email" text,
  "child_age" text,
  "message" text,
  "source" text not null default 'website'::text,
  "page" text,
  "utm" jsonb not null default '{}'::jsonb,
  "status" text not null default 'new'::text check (status = ANY (ARRAY['new'::text, 'contacted'::text, 'visit_booked'::text, 'enrolled'::text, 'closed'::text])),
  "email_status" text not null default 'pending'::text,
  "email_error" text,
  primary key ("id")
);

alter table public."pisipouk_leads" enable row level security;

-- pisipouk_events
create table if not exists public."pisipouk_events" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "session_id" text not null,
  "visitor_id" text,
  "event_type" text not null,
  "path" text,
  "referrer" text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "metadata" jsonb not null default '{}'::jsonb,
  "network_hash" text,
  "country" text,
  "region" text,
  "city" text,
  primary key ("id")
);

alter table public."pisipouk_events" enable row level security;

-- pisipouk_admins
create table if not exists public."pisipouk_admins" (
  "user_id" uuid not null,
  "email" text,
  "active" boolean not null default true,
  "created_at" timestamp with time zone not null default now(),
  primary key ("user_id")
);

alter table public."pisipouk_admins" enable row level security;

-- pisipouk_internal_visitors
create table if not exists public."pisipouk_internal_visitors" (
  "visitor_id" text not null,
  "excluded_at" timestamp with time zone not null default now(),
  primary key ("visitor_id")
);

alter table public."pisipouk_internal_visitors" enable row level security;

-- pisipouk_subscribers
create table if not exists public."pisipouk_subscribers" (
  "id" uuid not null default gen_random_uuid(),
  "email" text not null,
  "first_name" text,
  "status" text not null default 'active'::text check (status = ANY (ARRAY['active'::text, 'unsubscribed'::text])),
  "source" text not null default 'website'::text,
  "utm" jsonb not null default '{}'::jsonb,
  "consent_at" timestamp with time zone not null default now(),
  "unsubscribed_at" timestamp with time zone,
  "unsubscribe_token" uuid not null default gen_random_uuid(),
  "welcome_email_status" text not null default 'pending'::text,
  "welcome_email_error" text,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  primary key ("id")
);

alter table public."pisipouk_subscribers" enable row level security;

CREATE INDEX pisipouk_admin_sessions_expires_idx ON public.pisipouk_admin_sessions USING btree (expires_at);
CREATE UNIQUE INDEX pisipouk_admin_sessions_token_hash_key ON public.pisipouk_admin_sessions USING btree (token_hash);
CREATE INDEX pisipouk_events_created_at_idx ON public.pisipouk_events USING btree (created_at DESC);
CREATE INDEX pisipouk_events_event_type_idx ON public.pisipouk_events USING btree (event_type);
CREATE INDEX pisipouk_events_geo_idx ON public.pisipouk_events USING btree (country, region, city);
CREATE INDEX pisipouk_events_network_hash_idx ON public.pisipouk_events USING btree (network_hash) WHERE (network_hash IS NOT NULL);
CREATE INDEX pisipouk_events_session_idx ON public.pisipouk_events USING btree (session_id);
CREATE INDEX pisipouk_leads_created_at_idx ON public.pisipouk_leads USING btree (created_at DESC);
CREATE INDEX pisipouk_leads_status_idx ON public.pisipouk_leads USING btree (status);
CREATE INDEX pisipouk_messages_created_at_idx ON public.pisipouk_messages USING btree (created_at DESC);
CREATE INDEX pisipouk_messages_follow_up_idx ON public.pisipouk_messages USING btree (follow_up_at);
CREATE INDEX pisipouk_messages_status_idx ON public.pisipouk_messages USING btree (status);
CREATE INDEX pisipouk_reviews_published_idx ON public.pisipouk_reviews USING btree (is_published, is_featured);
CREATE INDEX pisipouk_subscribers_created_at_idx ON public.pisipouk_subscribers USING btree (created_at DESC);
CREATE UNIQUE INDEX pisipouk_subscribers_email_key ON public.pisipouk_subscribers USING btree (email);
CREATE INDEX pisipouk_subscribers_status_idx ON public.pisipouk_subscribers USING btree (status);
CREATE UNIQUE INDEX pisipouk_subscribers_unsubscribe_token_key ON public.pisipouk_subscribers USING btree (unsubscribe_token);

create or replace view public."pisipouk_daily_stats" as
 SELECT ((e.created_at AT TIME ZONE 'Europe/Athens'::text))::date AS day,
    count(*) FILTER (WHERE (e.event_type = 'page_view'::text)) AS page_views,
    count(DISTINCT e.session_id) FILTER (WHERE (e.event_type = 'page_view'::text)) AS sessions,
    count(*) FILTER (WHERE (e.event_type = ANY (ARRAY['phone_click'::text, 'viber_click'::text, 'email_click'::text, 'form_success'::text, 'visit_click'::text]))) AS cta_actions
   FROM (pisipouk_events e
     LEFT JOIN pisipouk_internal_visitors i ON ((i.visitor_id = e.visitor_id)))
  WHERE (i.visitor_id IS NULL)
  GROUP BY (((e.created_at AT TIME ZONE 'Europe/Athens'::text))::date)
  ORDER BY (((e.created_at AT TIME ZONE 'Europe/Athens'::text))::date) DESC;

