import { useEffect, useMemo, useState } from "react";
import { Download, Share2, Smartphone, X } from "lucide-react";
import { trackEvent } from "@/lib/pisipoukApi";

type InstallPromptEvent = Event & { prompt:()=>Promise<void>; userChoice:Promise<{outcome:"accepted"|"dismissed";platform:string}> };
type AppPlatform="ios"|"android"|"other";

function isStandalone(){return window.matchMedia?.("(display-mode: standalone)").matches||Boolean((navigator as Navigator & {standalone?:boolean}).standalone)}
function platform():AppPlatform{const ua=navigator.userAgent.toLowerCase();const isiPad=navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1;if(/iphone|ipad|ipod/.test(ua)||isiPad)return"ios";if(/android/.test(ua))return"android";return"other"}

function openDeepLink(){const target=new URLSearchParams(window.location.search).get("open");const labels:Record<string,RegExp>={games:/Παίζω/,create:/Δημιουργώ/,stories:/Ιστορίες/,stem:/Εξερευνώ/,music:/Κινούμαι/};const matcher=target?labels[target]:undefined;if(!matcher)return;window.setTimeout(()=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>(".v9-nav button,.v9-world"));buttons.find(b=>matcher.test(b.textContent||""))?.click()},220)}

export function PreschoolInstallV9(){
  const[deferred,setDeferred]=useState<InstallPromptEvent|null>(null);const[open,setOpen]=useState(false);const[installed,setInstalled]=useState(false);const os=useMemo(()=>(typeof navigator==="undefined"?"other":platform()),[]);
  useEffect(()=>{if(typeof window==="undefined")return;document.documentElement.dataset.pisipoukPlatform=os;document.documentElement.dataset.pisipoukStandalone=isStandalone()?"true":"false";setInstalled(isStandalone());openDeepLink();
    const onPrompt=(event:Event)=>{event.preventDefault();setDeferred(event as InstallPromptEvent)};const onInstalled=()=>{setInstalled(true);setOpen(false);document.documentElement.dataset.pisipoukStandalone="true";trackEvent("preschool_pwa_installed",{platform:os})};
    window.addEventListener("beforeinstallprompt",onPrompt);window.addEventListener("appinstalled",onInstalled);navigator.serviceWorker?.register("/pisipouk-sw.js",{scope:"/virtual-preschool/"}).catch(()=>undefined);
    return()=>{window.removeEventListener("beforeinstallprompt",onPrompt);window.removeEventListener("appinstalled",onInstalled);delete document.documentElement.dataset.pisipoukPlatform;delete document.documentElement.dataset.pisipoukStandalone};
  },[os]);
  if(installed)return <style>{platformStyles}</style>;
  const install=async()=>{trackEvent("preschool_pwa_install_open",{platform:os});if(os==="android"&&deferred){await deferred.prompt();const choice=await deferred.userChoice;trackEvent("preschool_pwa_install_result",{platform:os,outcome:choice.outcome});if(choice.outcome==="accepted")setInstalled(true);setDeferred(null);return}setOpen(true)};
  return <><button className="pisipouk-install-fab" onClick={install} aria-label="Εγκατάσταση του Πισιπούκ στο κινητό"><Smartphone size={20}/><span>{os==="ios"?"Στο iPhone / iPad":"Εγκατάσταση"}</span></button>{open&&<div className="pisipouk-install-sheet" role="dialog" aria-modal="true"><button className="pisipouk-install-close" onClick={()=>setOpen(false)}><X/></button><div className="pisipouk-install-icon"><img src="/favicon.webp" alt="Πισιπούκ"/></div><p className="eyebrow">Ο ΚΟΣΜΟΣ ΤΟΥ ΠΙΣΙΠΟΥΚ</p><h2>Βάλε τον Πισιπούκ στην αρχική οθόνη</h2>{os==="ios"?<div className="pisipouk-install-steps"><p><span>1</span><Share2/> Πάτησε <b>Κοινοποίηση</b> στο Safari.</p><p><span>2</span><Download/> Διάλεξε <b>Προσθήκη στην οθόνη Αφετηρίας</b>.</p><p><span>3</span>🎮 Το icon ανοίγει κατευθείαν στον κόσμο «Παίζω».</p></div>:<div className="pisipouk-install-steps"><p><span>1</span><Download/> Πάτησε <b>Εγκατάσταση</b>.</p><p><span>2</span>📲 Ο Πισιπούκ μπαίνει μαζί με τις εφαρμογές.</p><p><span>3</span>🎮 Με άνοιγμα πηγαίνει κατευθείαν στο «Παίζω».</p></div>}<small>Δεν απαιτείται παιδικός λογαριασμός. Η πρόοδος μένει τοπικά στη συσκευή.</small></div>}<style>{installStyles+platformStyles}</style></>
}

const installStyles=`
.pisipouk-install-fab{position:fixed;right:max(14px,env(safe-area-inset-right));bottom:max(14px,calc(env(safe-area-inset-bottom) + 12px));z-index:260;border:0;border-radius:999px;background:linear-gradient(135deg,#5f3ee9,#8a54f5);color:#fff;box-shadow:0 16px 38px #4833b457;padding:12px 17px;display:flex;align-items:center;gap:8px;font-weight:950}.pisipouk-install-sheet{position:fixed;z-index:400;left:50%;bottom:max(14px,env(safe-area-inset-bottom));transform:translateX(-50%);width:min(520px,calc(100% - 20px));border-radius:30px;background:#fffffff8;box-shadow:0 28px 90px #1f285757;padding:24px;color:#14215a}.pisipouk-install-close{position:absolute;right:14px;top:14px;border:0;border-radius:50%;width:44px;height:44px;display:grid;place-items:center;background:#f1efff;color:#6048dc}.pisipouk-install-icon{width:86px;height:86px;border-radius:24px;overflow:hidden;box-shadow:0 12px 28px #3647822e;margin-bottom:12px}.pisipouk-install-icon img{width:100%;height:100%;object-fit:cover}.pisipouk-install-sheet .eyebrow{font-size:.7rem;letter-spacing:.11em;font-weight:1000;color:#6d51ec;margin:0 0 6px}.pisipouk-install-sheet h2{font-size:1.55rem;line-height:1.05;margin:0 44px 16px 0}.pisipouk-install-steps{display:grid;gap:9px}.pisipouk-install-steps p{margin:0;display:flex;align-items:center;gap:9px;font-weight:800;line-height:1.35;background:#f7f8ff;border-radius:16px;padding:11px 12px}.pisipouk-install-steps p span{flex:0 0 28px;width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#ffd84f;color:#443d10;font-weight:1000}.pisipouk-install-sheet small{display:block;margin-top:14px;color:#6a7392;line-height:1.45}@media(max-width:720px){.pisipouk-install-fab{bottom:max(84px,calc(env(safe-area-inset-bottom) + 80px));padding:11px 14px}.pisipouk-install-fab span{font-size:.75rem}.pisipouk-install-sheet{bottom:max(8px,env(safe-area-inset-bottom));border-radius:28px 28px 24px 24px}}
`;
const platformStyles=`
html[data-pisipouk-platform="ios"] .v9-top{padding-top:max(6px,env(safe-area-inset-top))}html[data-pisipouk-platform="ios"] .v9-nav{backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px)}html[data-pisipouk-platform="ios"] .v9 button{min-height:44px}html[data-pisipouk-platform="ios"] .v9-panelhead{padding-top:env(safe-area-inset-top);height:calc(78px + env(safe-area-inset-top))}html[data-pisipouk-platform="ios"][data-pisipouk-standalone="true"] .v9{padding-bottom:env(safe-area-inset-bottom)}html[data-pisipouk-platform="android"] .v9 button{min-height:48px}html[data-pisipouk-platform="android"] .v9-world:active,html[data-pisipouk-platform="android"] .v9-card:active{transform:scale(.97)}@media(pointer:coarse) and (min-width:740px) and (max-width:1300px){.v9-panelbody{width:min(1180px,calc(100% - 24px))}.v9-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.v9-drawbar button{min-width:52px;min-height:52px}.v9-card,.v9-move{touch-action:manipulation}}
`;
