/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DailyLifeRouteImport } from './routes/daily-life'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as Espa20262027RouteImport } from './routes/espa-2026-2027'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as SafetyCareRouteImport } from './routes/safety-care'
import { Route as VirtualPreschoolRouteImport } from './routes/virtual-preschool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLifeRoute = DailyLifeRouteImport.update({
  id: '/daily-life',
  path: '/daily-life',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const Espa20262027Route = Espa20262027RouteImport.update({
  id: '/espa-2026-2027',
  path: '/espa-2026-2027',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyCareRoute = SafetyCareRouteImport.update({
  id: '/safety-care',
  path: '/safety-care',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualPreschoolRoute = VirtualPreschoolRouteImport.update({
  id: '/virtual-preschool',
  path: '/virtual-preschool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/espa-2026-2027': typeof Espa20262027Route
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/program': typeof ProgramRoute
  '/safety-care': typeof SafetyCareRoute
  '/virtual-preschool': typeof VirtualPreschoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/espa-2026-2027': typeof Espa20262027Route
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/program': typeof ProgramRoute
  '/safety-care': typeof SafetyCareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/espa-2026-2027': typeof Espa20262027Route
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/program': typeof ProgramRoute
  '/safety-care': typeof SafetyCareRoute
  '/virtual-preschool': typeof VirtualPreschoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/espa-2026-2027'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/nutrition'
    | '/philosophy'
    | '/program'
    | '/safety-care'
    | '/virtual-preschool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/espa-2026-2027'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/nutrition'
    | '/philosophy'
    | '/program'
    | '/safety-care'
    | '/virtual-preschool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/espa-2026-2027'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/nutrition'
    | '/philosophy'
    | '/program'
    | '/safety-care'
    | '/virtual-preschool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookVisitRoute: typeof BookVisitRoute
  ContactRoute: typeof ContactRoute
  DailyLifeRoute: typeof DailyLifeRoute
  EnrollmentRoute: typeof EnrollmentRoute
  Espa20262027Route: typeof Espa20262027Route
  FacilitiesRoute: typeof FacilitiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NutritionRoute: typeof NutritionRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProgramRoute: typeof ProgramRoute
  SafetyCareRoute: typeof SafetyCareRoute
  VirtualPreschoolRoute: typeof VirtualPreschoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-life': {
      id: '/daily-life'
      path: '/daily-life'
      fullPath: '/daily-life'
      preLoaderRoute: typeof DailyLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espa-2026-2027': {
      id: '/espa-2026-2027'
      path: '/espa-2026-2027'
      fullPath: '/espa-2026-2027'
      preLoaderRoute: typeof Espa20262027RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-care': {
      id: '/safety-care'
      path: '/safety-care'
      fullPath: '/safety-care'
      preLoaderRoute: typeof SafetyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-preschool': {
      id: '/virtual-preschool'
      path: '/virtual-preschool'
      fullPath: '/virtual-preschool'
      preLoaderRoute: typeof VirtualPreschoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookVisitRoute: BookVisitRoute,
  ContactRoute: ContactRoute,
  DailyLifeRoute: DailyLifeRoute,
  EnrollmentRoute: EnrollmentRoute,
  Espa20262027Route: Espa20262027Route,
  FacilitiesRoute: FacilitiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NutritionRoute: NutritionRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProgramRoute: ProgramRoute,
  SafetyCareRoute: SafetyCareRoute,
  VirtualPreschoolRoute: VirtualPreschoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
