/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SafetyCareRouteImport } from './routes/safety-care'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as DailyLifeRouteImport } from './routes/daily-life'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchoolYearsRouteImport } from './routes/admin.school-years'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminParentsRouteImport } from './routes/admin.parents'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminMenuCostingRouteImport } from './routes/admin.menu-costing'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminFamiliesRouteImport } from './routes/admin.families'
import { Route as AdminConsentsRouteImport } from './routes/admin.consents'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminChildrenRouteImport } from './routes/admin.children'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBudgetRouteImport } from './routes/admin.budget'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminSchoolYearsNewRouteImport } from './routes/admin.school-years.new'
import { Route as ApiPublicCalendarIcsRouteImport } from './routes/api/public/calendar.ics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyCareRoute = SafetyCareRouteImport.update({
  id: '/safety-care',
  path: '/safety-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLifeRoute = DailyLifeRouteImport.update({
  id: '/daily-life',
  path: '/daily-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolYearsRoute = AdminSchoolYearsRouteImport.update({
  id: '/school-years',
  path: '/school-years',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParentsRoute = AdminParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuCostingRoute = AdminMenuCostingRouteImport.update({
  id: '/menu-costing',
  path: '/menu-costing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFamiliesRoute = AdminFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsentsRoute = AdminConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChildrenRoute = AdminChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetRoute = AdminBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolYearsNewRoute = AdminSchoolYearsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSchoolYearsRoute,
} as any)
const ApiPublicCalendarIcsRoute = ApiPublicCalendarIcsRouteImport.update({
  id: '/api/public/calendar/ics',
  path: '/api/public/calendar/ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-care': typeof SafetyCareRoute
  '/teacher': typeof TeacherRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/budget': typeof AdminBudgetRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu-costing': typeof AdminMenuCostingRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/school-years': typeof AdminSchoolYearsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/school-years/new': typeof AdminSchoolYearsNewRoute
  '/api/public/calendar/ics': typeof ApiPublicCalendarIcsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-care': typeof SafetyCareRoute
  '/teacher': typeof TeacherRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/budget': typeof AdminBudgetRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu-costing': typeof AdminMenuCostingRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/school-years': typeof AdminSchoolYearsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/school-years/new': typeof AdminSchoolYearsNewRoute
  '/api/public/calendar/ics': typeof ApiPublicCalendarIcsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/enrollment': typeof EnrollmentRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/philosophy': typeof PhilosophyRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-care': typeof SafetyCareRoute
  '/teacher': typeof TeacherRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/budget': typeof AdminBudgetRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu-costing': typeof AdminMenuCostingRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/school-years': typeof AdminSchoolYearsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/school-years/new': typeof AdminSchoolYearsNewRoute
  '/api/public/calendar/ics': typeof ApiPublicCalendarIcsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/login'
    | '/nutrition'
    | '/philosophy'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/reset-password'
    | '/safety-care'
    | '/teacher'
    | '/terms'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/budget'
    | '/admin/calendar'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/consents'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/incidents'
    | '/admin/leads'
    | '/admin/menu-costing'
    | '/admin/menus'
    | '/admin/organization'
    | '/admin/parents'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/school-years'
    | '/admin/users'
    | '/admin/'
    | '/admin/school-years/new'
    | '/api/public/calendar/ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/login'
    | '/nutrition'
    | '/philosophy'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/reset-password'
    | '/safety-care'
    | '/teacher'
    | '/terms'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/budget'
    | '/admin/calendar'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/consents'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/incidents'
    | '/admin/leads'
    | '/admin/menu-costing'
    | '/admin/menus'
    | '/admin/organization'
    | '/admin/parents'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/school-years'
    | '/admin/users'
    | '/admin'
    | '/admin/school-years/new'
    | '/api/public/calendar/ics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book-visit'
    | '/contact'
    | '/daily-life'
    | '/enrollment'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/login'
    | '/nutrition'
    | '/philosophy'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/reset-password'
    | '/safety-care'
    | '/teacher'
    | '/terms'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/budget'
    | '/admin/calendar'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/consents'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/incidents'
    | '/admin/leads'
    | '/admin/menu-costing'
    | '/admin/menus'
    | '/admin/organization'
    | '/admin/parents'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/school-years'
    | '/admin/users'
    | '/admin/'
    | '/admin/school-years/new'
    | '/api/public/calendar/ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  BookVisitRoute: typeof BookVisitRoute
  ContactRoute: typeof ContactRoute
  DailyLifeRoute: typeof DailyLifeRoute
  EnrollmentRoute: typeof EnrollmentRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyCareRoute: typeof SafetyCareRoute
  TeacherRoute: typeof TeacherRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCalendarIcsRoute: typeof ApiPublicCalendarIcsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-care': {
      id: '/safety-care'
      path: '/safety-care'
      fullPath: '/safety-care'
      preLoaderRoute: typeof SafetyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-life': {
      id: '/daily-life'
      path: '/daily-life'
      fullPath: '/daily-life'
      preLoaderRoute: typeof DailyLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/school-years': {
      id: '/admin/school-years'
      path: '/school-years'
      fullPath: '/admin/school-years'
      preLoaderRoute: typeof AdminSchoolYearsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parents': {
      id: '/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AdminParentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-costing': {
      id: '/admin/menu-costing'
      path: '/menu-costing'
      fullPath: '/admin/menu-costing'
      preLoaderRoute: typeof AdminMenuCostingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/families': {
      id: '/admin/families'
      path: '/families'
      fullPath: '/admin/families'
      preLoaderRoute: typeof AdminFamiliesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consents': {
      id: '/admin/consents'
      path: '/consents'
      fullPath: '/admin/consents'
      preLoaderRoute: typeof AdminConsentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/children': {
      id: '/admin/children'
      path: '/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AdminChildrenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budget': {
      id: '/admin/budget'
      path: '/budget'
      fullPath: '/admin/budget'
      preLoaderRoute: typeof AdminBudgetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/school-years/new': {
      id: '/admin/school-years/new'
      path: '/new'
      fullPath: '/admin/school-years/new'
      preLoaderRoute: typeof AdminSchoolYearsNewRouteImport
      parentRoute: typeof AdminSchoolYearsRoute
    }
    '/api/public/calendar/ics': {
      id: '/api/public/calendar/ics'
      path: '/api/public/calendar/ics'
      fullPath: '/api/public/calendar/ics'
      preLoaderRoute: typeof ApiPublicCalendarIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSchoolYearsRouteChildren {
  AdminSchoolYearsNewRoute: typeof AdminSchoolYearsNewRoute
}

const AdminSchoolYearsRouteChildren: AdminSchoolYearsRouteChildren = {
  AdminSchoolYearsNewRoute: AdminSchoolYearsNewRoute,
}

const AdminSchoolYearsRouteWithChildren =
  AdminSchoolYearsRoute._addFileChildren(AdminSchoolYearsRouteChildren)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBudgetRoute: typeof AdminBudgetRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminChildrenRoute: typeof AdminChildrenRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminConsentsRoute: typeof AdminConsentsRoute
  AdminFamiliesRoute: typeof AdminFamiliesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMenuCostingRoute: typeof AdminMenuCostingRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminParentsRoute: typeof AdminParentsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSchoolYearsRoute: typeof AdminSchoolYearsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBudgetRoute: AdminBudgetRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminChildrenRoute: AdminChildrenRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminConsentsRoute: AdminConsentsRoute,
  AdminFamiliesRoute: AdminFamiliesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMenuCostingRoute: AdminMenuCostingRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminParentsRoute: AdminParentsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSchoolYearsRoute: AdminSchoolYearsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  BookVisitRoute: BookVisitRoute,
  ContactRoute: ContactRoute,
  DailyLifeRoute: DailyLifeRoute,
  EnrollmentRoute: EnrollmentRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  PhilosophyRoute: PhilosophyRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyCareRoute: SafetyCareRoute,
  TeacherRoute: TeacherRoute,
  TermsRoute: TermsRoute,
  ApiPublicCalendarIcsRoute: ApiPublicCalendarIcsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}